apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
        resources:
          requests:
            memory: "256Mi"  # Minimum memory the pod is guaranteed
            cpu: "200m"       # Minimum CPU the pod is guaranteed
          limits:
            memory: "512Mi"  # Maximum memory the pod can use
            cpu: "500m"       # Maximum CPU the pod can use
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager/
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager

