apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prometheus-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus
  minReplicas: 1          # Minimum number of pods
  maxReplicas: 3         # Maximum number of pods
  targetCPUUtilizationPercentage: 70  # Target CPU utilization percentage
