apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
      - endpoints
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch
