apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "512Mi" 
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-certs
          mountPath: /etc/prometheus/secrets
          readOnly: true
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
          items:
            - key: "prometheus.yml"
              path: "prometheus.yml"
            - key: "alert_rules.yml"
              path: "alert_rules.yml"
      - name: prometheus-certs
        secret:
          secretName: prometheus-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus

