apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1          # Minimum number of pods
  maxReplicas: 3         # Maximum number of pods
  targetCPUUtilizationPercentage: 60  # Target CPU utilization percentage

